# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Promises&Codeables' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Promises&Codeables
    pod "PromiseKit", "~> 6.0"
    pod 'PromiseKit/Alamofire'
    pod 'Alamofire', '~> 4.7'
   pod 'SVProgressHUD'
  target 'Promises&CodeablesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Promises&CodeablesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
